#!/bin/bash
#
# muutujate kasutamise näide
#
# definerime muutuja ja omamiste väärtusõ
# väärtus saadakse whoami käsust
kasutaja=`whoami`
#väljastame muutuja väärtus koos seletusega
echo "Tere, $kasutaja"
#
kell=`date +"%H:%M"`
eco "Kell on $kell"
