#!/bin/bash
#
# Kontroillime arvu positiivsuse olekut
#
# Küsime väärtused kasutaja käest
echo -n "Sisesta arv: "
read arv
# Kontrollime, kas arv on positiivne
# sel juhul peab olema suurem kui 0
if [ $arv -gt 0 ] ; then
    echo "$arv on positiivne"
# eld tähendab juhul kui. Kui väärtus on negatiivne
# siis arv peab olema väiksem kui 0
elif [ $arv -lt 0 ] ; then
   echo "$arv on negatiivne"
# If lause tuleb korralikult lõpetada
# Kui esimene tingimus või teine tingumus ei sobinud siis kasuta else osa
else
   echo "$arv on neutraalne"
# if lause tuleb korralikult lõpetada
fi
